docker:
  image: yegor256/java8
install: |
  sudo gem install --no-rdoc --no-ri pdd
  sudo gem install --no-rdoc --no-ri xcop
env:
  MAVEN_OPTS: -Xmx1g
  JAVA_OPTS: -Xmx1g
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pog -Psonatype --errors --settings /home/r/settings.xml