decrypt:
  settings.xml: "settings.xml.asc"
  pubring.gpg: "pub.gpg.asc"
  secring.gpg: "sec.gpg.asc"
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pjcabi --settings /home/r/settings.xml