language: java
sudo: false # faster builds
cache:
  directories:
    - $HOME/.m2
script:
  - mvn clean install --errors --batch-mode
jdk:
  - oraclejdk8
after_success:
  - "bash <(curl -s https://codecov.io/bash)"